name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-scan-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build + Test (JaCoCo)
        run: mvn -B clean test

      # âœ… ADD THIS STEP (creates target/*.jar)
      - name: Package JAR (no tests)
        run: mvn -B -DskipTests package

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          if-no-files-found: error

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar \
            -Dsonar.projectKey=itzakshada_devops-spring-app \
            -Dsonar.organization=itzakshada \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -------- DEPLOYMENT STARTS HERE --------
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@4.188.82.126
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker login petclinic.azurecr.io \
            -u ${{ secrets.ACR_USERNAME }} \
            -p ${{ secrets.ACR_PASSWORD }}

            docker pull petclinic.azurecr.io/rest-service-app:latest

            docker stop app || true
            docker rm app || true

            docker run -d \
            -p 9090:8080 \
            --name app \
            petclinic.azurecr.io/rest-service-app:latest
